<a href="https://colab.research.google.com/github/tanvisonawane34/Python-Libraries/blob/main/Assignment14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create a 5x6 array with random numbers from 10 to 100
a = np.random.randint(10, 101, (5, 6))

# Print the array
print("Array:")
print(a)

# Print shape,size and datatype
print("\nShape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)

Array:
[[31 13 30 31 71 55]
 [86 80 21 72 81 19]
 [84 61 70 24 37 17]
 [60 34 10 87 62 59]
 [76 88 18 91 32 43]]

Shape: (5, 6)
Size: 30
Data Type: int64


In [ ]:
import numpy as np

# Create a 1D array with 20 random numbers from 1 to 50
a = np.random.randint(1, 51, 20)

# Print the array
print("Array:")
print(a)

# Print minimum value and index
print("\nMinimum Value:", a.min())
print("Index of Minimum Value:", a.argmin())

# Print maximum value and index
print("\nMaximum Value:", a.max())
print("Index of Maximum Value:", a.argmax())

# Sum, mean & standard deviation
print("\nSum:", a.sum())
print("Mean:", a.mean())
print("Standard Deviation:", a.std())

Array:
[50 35 50  9 11 19 23  1 38 46 32 26 32 20 13 24  3 28 49 12]

Minimum Value: 1
Index of Minimum Value: 7

Maximum Value: 50
Index of Maximum Value: 0

Sum: 521
Mean: 26.05
Standard Deviation: 15.021567827627049


In [ ]:
import numpy as np

# Create a 4x5 matrix with random numbers from 20 to 80
a = np.random.randint(20, 81, (4, 5))

# Print the matrix
print("Matrix:")
print(a)

# Statistical values
print("\nMinimum Value:", a.min())
print("Maximum Value:", a.max())
print("Sum:", a.sum())
print("Mean:", a.mean())
print("Standard Deviation:", a.std())

# Sum of each row
print("\nSum of Each Row:")
print(a.sum(axis=1))

# Sum of each column
print("\nSum of Each Column:")
print(a.sum(axis=0))

Matrix:
[[40 40 48 80 40]
 [77 48 70 56 65]
 [61 22 57 45 29]
 [56 49 66 56 44]]

Minimum Value: 22
Maximum Value: 80
Sum: 1049
Mean: 52.45
Standard Deviation: 14.5995719115322

Sum of Each Row:
[248 316 214 271]

Sum of Each Column:
[234 159 241 237 178]


In [ ]:
import numpy as np

# Create a 1D array from 1 to 24
arr = np.arange(1, 25)

print("Original Array:")
print(a)
print("Shape:", arr.shape)

# Reshape into 4 x 6
b = arr.reshape(4, 6)
print("\n4 x 6 Array:")
print(b)
print("Shape:", b.shape)

# Reshape into 3 x 8
c = arr.reshape(3, 8)
print("\n3 x 8 Array:")
print(c)
print("Shape:", c.shape)

# Reshape into 2 x 3 x 4
d = arr.reshape(2, 3, 4)
print("\n2 x 3 x 4 Array:")
print(d)
print("Shape:", d.shape)

Original Array:
[[40 40 48 80 40]
 [77 48 70 56 65]
 [61 22 57 45 29]
 [56 49 66 56 44]]
Shape: (24,)

4 x 6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

3 x 8 Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

2 x 3 x 4 Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
import numpy as np

# Create the array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Array:")
print(arr)

# Extracting First row
print("\nFirst Row:")
print(arr[0])

# Extracting Last column
print("\nLast Column:")
print(arr[:, 3])

# Extracting center 2 x 2 submatrix
print("\nCenter 2 x 2 Submatrix:")
print(arr[1:3, 1:3])

# Extracting all even numbers
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2 x 2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:
import numpy as np

# Create 5 x 5 matrix with random numbers from 1 to 100
arr = np.random.randint(1, 101, (5, 5))

print("Matrix:")
print(arr)

# Print diagonal elements
print("\nDiagonal Elements:")
print(arr.diagonal())

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace elements less than 30 with 0
arr[arr < 30] = 0

# Print modified array
print("\nModified Array:")
print(arr)

Matrix:
[[74 49  4 91 78]
 [11 14 13 64 18]
 [86 19 25 47 43]
 [21  3 66  8 30]
 [ 4 16 22 32  1]]

Diagonal Elements:
[74 14 25  8  1]

Elements Greater Than 50:
[74 91 78 64 86 66]

Modified Array:
[[74 49  0 91 78]
 [ 0  0  0 64  0]
 [86  0  0 47 43]
 [ 0  0 66  0 30]
 [ 0  0  0 32  0]]


In [ ]:
import numpy as np

# Create the arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Addition
print("Addition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)

# Element-wise power
print("\nPower:")
print(a ** b)

# Modulo operation
print("\nModulo:")
print(a % b)

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Power:
[     10     400   27000 2560000]

Modulo:
[0 0 0 0]


In [ ]:
import numpy as np

# Create the matrices
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Element-wise multiplication
print("Element-wise Multiplication :")
print(a * b)

# Matrix multiplication
print("\nMatrix Multiplication :")
print(a @ b)

# Difference :
# * multiplies numbers at the same position
# @ multiplies rows of the first matrix with columns of the second matrix

Element-wise Multiplication :
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
import numpy as np

# Create a 6 x 6 matrix with random numbers
arr = np.random.randn(6, 6)

print("Matrix:")
print(arr)

# Print properties
print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

# Index of maximum and minimum value
print("\nIndex of Maximum Value:", arr.argmax())
print("Index of Minimum Value:", arr.argmin())

# Top-left 3 x 3 submatrix
print("\nTop-left 3 x 3 Submatrix:")
print(arr[0:3, 0:3])

# Replace negative numbers with absolute values
arr = np.abs(arr)

print("\nModified Matrix:")
print(arr)

# Print mean of modified matrix
print("\nMean:", arr.mean())

Matrix:
[[-0.36459486 -0.73356493 -0.73513813 -0.88305417  0.6607744  -0.04116394]
 [ 0.46147086  0.28666739  0.90663287  1.36395859  0.3836103   1.85880652]
 [-0.40233998 -0.39397241  0.23349617  1.83484417  1.16906732  1.93063012]
 [-1.17793494  0.08645158 -0.01415383  0.12113883 -0.20810761  1.53092817]
 [ 0.99826242 -0.29007902 -0.79838697 -0.0312654   0.28717657 -1.12955861]
 [ 0.82944078 -2.56267791  1.34773502 -0.03582378 -1.1096786   0.74073206]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: 17
Index of Minimum Value: 31

Top-left 3 x 3 Submatrix:
[[-0.36459486 -0.73356493 -0.73513813]
 [ 0.46147086  0.28666739  0.90663287]
 [-0.40233998 -0.39397241  0.23349617]]

Modified Matrix:
[[0.36459486 0.73356493 0.73513813 0.88305417 0.6607744  0.04116394]
 [0.46147086 0.28666739 0.90663287 1.36395859 0.3836103  1.85880652]
 [0.40233998 0.39397241 0.23349617 1.83484417 1.16906732 1.93063012]
 [1.17793494 0.08645158 0.01415383 0.12113883 0.20810761 1.53092817]
 [0.

In [ ]:
import numpy as np

# Create a 10 x 5 array with random marks from 30 to 100
arr = np.random.randint(30, 101, (10, 5))

# Print the marks
print("Student Marks:")
print(arr)

# Calculate total marks of each student
total = arr.sum(axis=1)
print("\nTotal Marks:")
print(total)

# Calculate average marks of each student
average = arr.mean(axis=1)
print("\nAverage Marks:")
print(average)

# Find the student with the highest total marks
high = total.argmax()
print("\nStudent with Highest Total Marks:", high)
print("Marks:", arr[high])
print("Total:", total[high])

# Find the student with the lowest total marks
low = total.argmin()
print("\nStudent with Lowest Total Marks:", low)
print("Marks:", arr[low])
print("Total:", total[low])

# Calculate overall class mean and standard deviation
print("\nClass Mean:", arr.mean())
print("Class Standard Deviation:", arr.std())

# Reshape the array
new_arr = arr.reshape(5, 10)
print("\nReshaped Array (5 x 10):")
print(new_arr)

# Find the top 3 students based on total marks
top = total.argsort()[-3:]

# Print marks of the top 3 students
print("\nMarks of Top 3 Students:")
print(arr[top])

Student Marks:
[[ 98  64  57  51  65]
 [ 71  77  64  61  88]
 [ 77  83  30 100  47]
 [ 73  92  83  30  55]
 [ 60  71  89  95  61]
 [ 86  32  45  47  55]
 [ 42  36  53  47  36]
 [ 87  87  90  69  99]
 [ 64  43  66  95  99]
 [ 68  99  30  82  50]]

Total Marks:
[335 361 337 333 376 265 214 432 367 329]

Average Marks:
[67.  72.2 67.4 66.6 75.2 53.  42.8 86.4 73.4 65.8]

Student with Highest Total Marks: 7
Marks: [87 87 90 69 99]
Total: 432

Student with Lowest Total Marks: 6
Marks: [42 36 53 47 36]
Total: 214

Class Mean: 66.98
Class Standard Deviation: 21.147567235973032

Reshaped Array (5 x 10):
[[ 98  64  57  51  65  71  77  64  61  88]
 [ 77  83  30 100  47  73  92  83  30  55]
 [ 60  71  89  95  61  86  32  45  47  55]
 [ 42  36  53  47  36  87  87  90  69  99]
 [ 64  43  66  95  99  68  99  30  82  50]]

Marks of Top 3 Students:
[[64 43 66 95 99]
 [60 71 89 95 61]
 [87 87 90 69 99]]
