<a href="https://colab.research.google.com/github/tanvisonawane34/Python-Libraries/blob/main/Assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)
print("Shape :",arr1.shape)
print("Datatype :",arr1.dtype)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print("Shape :",arr2.shape)
print("Datatype :",arr2.dtype)



[10 20 30 40 50]
Shape : (5,)
Datatype : int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
Datatype : int64


In [ ]:
import numpy as np
arr = np.zeros(8)
print("1D Array of 8 zeros :")
print(arr)

arr2 = np.ones((4,4))
print("\n2D Array of ones :")
print(arr2)

arr3 = np.zeros((3,3))
print("\n3x3 matrix of zeros :")
print(arr3)

1D Array of 8 zeros :
[0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of ones :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 matrix of zeros :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr = np.arange(0,21,1)
print("Number from 0 to 20 :")
print(arr)

arr2 = np.arange(10,51,2)
print("\nEven nos from 10 to 50")
print(arr2)

arr3 = np.arange(5,101,5)
print("\nNos from 5 to 100 with step of 5 :")
print(arr3)

Number from 0 to 20 :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even nos from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Nos from 5 to 100 with step of 5 :
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
import numpy as np
arr = np.linspace(0,5,10)
print("10 equally spaced nos between 0 & 5 :")
print(arr)
print("Length :", len(arr))

arr2 = np.linspace(-10,10,15)
print("\n15 equally spaced nos between -10 & 10 :")
print(arr2)
print("Length :",len(arr2))



10 equally spaced nos between 0 & 5 :
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length : 10

15 equally spaced nos between -10 & 10 :
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length : 15


In [ ]:
import numpy as np
arr = np.random.rand(10)
print("10 random nos between 0 & 1 :")
print(arr)

arr2 = np.random.randn(3,3)
print("\nA 3x3 matrix of random nos :")
print(arr2)

arr3 = np.random.randint(10,51,(4,5))
print("\n2D Array of random integers between 10 to 50 :")
print(arr3)

10 random nos between 0 & 1 :
[0.3609295  0.02371304 0.37643783 0.69170255 0.00151955 0.21363833
 0.80751264 0.98986724 0.33904731 0.02500006]

A 3x3 matrix of random nos :
[[ 0.37406733 -0.57635465 -1.86271517]
 [ 1.30695638  0.19993074 -0.56538268]
 [ 0.1235498   1.02279127 -0.46910254]]

2D Array of random integers between 10 to 50 :
[[34 47 33 26 33]
 [48 18 29 41 31]
 [13 32 31 10 22]
 [13 36 50 35 25]]


In [ ]:
import numpy as np
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Vector 1 :")
print(v1)

print("\nVector 2 :")
print(v2)

print("\nAddition :")
print(v1 + v2)

print("\nSubtraction :")
print(v1 - v2)

print("\nElement-wise Multiplication :")
print(v1 * v2)

print("\nDot Product:")
print(np.dot(v1, v2))

Vector 1 :
[2 4 6 8]

Vector 2 :
[1 3 5 7]

Addition :
[ 3  7 11 15]

Subtraction :
[1 1 1 1]

Element-wise Multiplication :
[ 2 12 30 56]

Dot Product:
100


In [ ]:
from os import PRIO_PGRP
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Vector 1 :")
print(A)
print("\nVector 2 :")
print(B)

print("\nMatrix Addition : ")
print(A + B)
print("\nMatrix Multiplication : ")
print(A @ B)
print("\nElement-wise multiplication : ")
print(A * B)

Vector 1 :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector 2 :
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition : 
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication : 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise multiplication : 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
import numpy as np
arr = np.random.randint(1,101,(4,4))
print("4X4 matrix of random integers :")
print(arr)

print("\nShape :",arr.shape)
print("Dimension :",arr.ndim)
print("Size :",arr.size)
print("Datatype :",arr.dtype)
print("Minimum value :",arr.min())
print("Maximum value :",arr.max())

4X4 matrix of random integers :
[[37 26 77  8]
 [46 70 63 27]
 [90 90 49 21]
 [18 76 50 86]]

Shape : (4, 4)
Dimension : 2
Size : 16
Datatype : int64
Minimum value : 8
Maximum value : 90


In [ ]:
import numpy as np
arr = np.random.randint(1,51,(20))
print("1D array :")
print(arr)

matrix = arr.reshape(4,5)
print("\n4x5 Matrix :")
print(matrix)

print("\nSum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())

print("\nMaximum Value in Each Row:")
print(matrix.max(axis=1))

1D array :
[45 39  8  6 43 22 29 33 37 32 47 23 21 39 16 36  6 26  5  1]

4x5 Matrix :
[[45 39  8  6 43]
 [22 29 33 37 32]
 [47 23 21 39 16]
 [36  6 26  5  1]]

Sum: 514
Mean: 25.7
Standard Deviation: 14.286707108357755

Maximum Value in Each Row:
[45 37 47 36]


In [ ]:
# Import numpy
import numpy as np

# Exception handling
try :

  # Ask the user to enter numbers to generate
  num = int(input("Enter numbers to Generate : "))
  # To print random nos between 1-100
  arr = np.random.randint(10,101,(num))
  print("Generated array : ")
  print(arr)

  # To print the math functions
  print("\nMean :",arr.mean())
  print("Median :",np.median(arr))
  print("Standard Deviation :",arr.std())
  print("Minimum value :",arr.min())
  print("Maximum value :",arr.max())

  # Converting the array into 2D array
  if num % 2 == 0:
      matrix = arr.reshape(2, num // 2)

      print("\n2D Array:")
      print(matrix)

      print("\nRow-wise Sum:")
      print(matrix.sum(axis=1))

  else:
      print("\nCannot reshape into a 2D array because the number of elements is odd.")

# Except block
except ValueError :
  print("Please enter a valid number :")



Enter numbers to Generate : 20
Generated array : 
[69 55 44 76 84 12 48 74 13 74 23 65 38 91 43 52 73 89 92 14]

Mean : 56.45
Median : 60.0
Standard Deviation : 25.819517811144344
Minimum value : 12
Maximum value : 92

2D Array:
[[69 55 44 76 84 12 48 74 13 74]
 [23 65 38 91 43 52 73 89 92 14]]

Row-wise Sum:
[549 580]
